//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nekretnine.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nekretnine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string actions_table {
            get {
                return ResourceManager.GetString("actions_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        internal static string activate_button {
            get {
                return ResourceManager.GetString("activate_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activated.
        /// </summary>
        internal static string activated {
            get {
                return ResourceManager.GetString("activated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activated Agents.
        /// </summary>
        internal static string activated_agents {
            get {
                return ResourceManager.GetString("activated_agents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Offers.
        /// </summary>
        internal static string active_offers {
            get {
                return ResourceManager.GetString("active_offers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Realestate.
        /// </summary>
        internal static string add_realestate {
            get {
                return ResourceManager.GetString("add_realestate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agents.
        /// </summary>
        internal static string agents {
            get {
                return ResourceManager.GetString("agents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string all_selection {
            get {
                return ResourceManager.GetString("all_selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string browse {
            get {
                return ResourceManager.GetString("browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string city {
            get {
                return ResourceManager.GetString("city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &apos;Details&apos; to view contract details..
        /// </summary>
        internal static string click_details {
            get {
                return ResourceManager.GetString("click_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        internal static string client {
            get {
                return ResourceManager.GetString("client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Contracts.
        /// </summary>
        internal static string completed_contracts {
            get {
                return ResourceManager.GetString("completed_contracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password:.
        /// </summary>
        internal static string confirm_passwd {
            get {
                return ResourceManager.GetString("confirm_passwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        internal static string content {
            get {
                return ResourceManager.GetString("content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract.
        /// </summary>
        internal static string contract {
            get {
                return ResourceManager.GetString("contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract content.
        /// </summary>
        internal static string contract_content {
            get {
                return ResourceManager.GetString("contract_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Details.
        /// </summary>
        internal static string contract_details {
            get {
                return ResourceManager.GetString("contract_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract ID.
        /// </summary>
        internal static string contract_id {
            get {
                return ResourceManager.GetString("contract_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Type.
        /// </summary>
        internal static string contract_type {
            get {
                return ResourceManager.GetString("contract_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contracts.
        /// </summary>
        internal static string contracts {
            get {
                return ResourceManager.GetString("contracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Contract.
        /// </summary>
        internal static string create_contract {
            get {
                return ResourceManager.GetString("create_contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Offer.
        /// </summary>
        internal static string create_offer {
            get {
                return ResourceManager.GetString("create_offer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been created successfully. You must wait until an administrator activates your account before you can use it..
        /// </summary>
        internal static string create_success {
            get {
                return ResourceManager.GetString("create_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string dark {
            get {
                return ResourceManager.GetString("dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date: .
        /// </summary>
        internal static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate.
        /// </summary>
        internal static string deactivate_button {
            get {
                return ResourceManager.GetString("deactivate_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivated.
        /// </summary>
        internal static string deactivated {
            get {
                return ResourceManager.GetString("deactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivated Agents.
        /// </summary>
        internal static string deactivated_agents {
            get {
                return ResourceManager.GetString("deactivated_agents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string details {
            get {
                return ResourceManager.GetString("details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer Details.
        /// </summary>
        internal static string details_offer {
            get {
                return ResourceManager.GetString("details_offer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realestate Details.
        /// </summary>
        internal static string details_realestate {
            get {
                return ResourceManager.GetString("details_realestate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Offer.
        /// </summary>
        internal static string edit_offer {
            get {
                return ResourceManager.GetString("edit_offer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Realestate.
        /// </summary>
        internal static string edit_realestate {
            get {
                return ResourceManager.GetString("edit_realestate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string email_table {
            get {
                return ResourceManager.GetString("email_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords do not match..
        /// </summary>
        internal static string error_confirm_pass {
            get {
                return ResourceManager.GetString("error_confirm_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content cannot be empty..
        /// </summary>
        internal static string error_content_empty {
            get {
                return ResourceManager.GetString("error_content_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving contract. Please try again later..
        /// </summary>
        internal static string error_contract {
            get {
                return ResourceManager.GetString("error_contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email..
        /// </summary>
        internal static string error_email {
            get {
                return ResourceManager.GetString("error_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 8 characters long..
        /// </summary>
        internal static string error_password {
            get {
                return ResourceManager.GetString("error_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid phone number. Use digits only, 7-15 characters..
        /// </summary>
        internal static string error_phone {
            get {
                return ResourceManager.GetString("error_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving realestate. Try again later..
        /// </summary>
        internal static string error_realestate {
            get {
                return ResourceManager.GetString("error_realestate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client not selected..
        /// </summary>
        internal static string error_select_client {
            get {
                return ResourceManager.GetString("error_select_client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed date not selected..
        /// </summary>
        internal static string error_signed_date {
            get {
                return ResourceManager.GetString("error_signed_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid square meterage. Only numbers allowed..
        /// </summary>
        internal static string error_square_meterage {
            get {
                return ResourceManager.GetString("error_square_meterage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username can only contain letters and numbers..
        /// </summary>
        internal static string error_username {
            get {
                return ResourceManager.GetString("error_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validity period must be a number greater than zero..
        /// </summary>
        internal static string error_valid_period {
            get {
                return ResourceManager.GetString("error_valid_period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string filter {
            get {
                return ResourceManager.GetString("filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name:.
        /// </summary>
        internal static string first_name {
            get {
                return ResourceManager.GetString("first_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string firstname_table {
            get {
                return ResourceManager.GetString("firstname_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flame.
        /// </summary>
        internal static string flame {
            get {
                return ResourceManager.GetString("flame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Rent.
        /// </summary>
        internal static string for_rent {
            get {
                return ResourceManager.GetString("for_rent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Sale.
        /// </summary>
        internal static string for_sale {
            get {
                return ResourceManager.GetString("for_sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Offer.
        /// </summary>
        internal static string has_offer {
            get {
                return ResourceManager.GetString("has_offer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account? .
        /// </summary>
        internal static string have_acc {
            get {
                return ResourceManager.GetString("have_acc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        internal static string images {
            get {
                return ResourceManager.GetString("images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbox.
        /// </summary>
        internal static string inbox {
            get {
                return ResourceManager.GetString("inbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inquiries.
        /// </summary>
        internal static string inquiries {
            get {
                return ResourceManager.GetString("inquiries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid price. Use only numbers..
        /// </summary>
        internal static string invalid_price {
            get {
                return ResourceManager.GetString("invalid_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password..
        /// </summary>
        internal static string invalid_user_or_pass {
            get {
                return ResourceManager.GetString("invalid_user_or_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name:.
        /// </summary>
        internal static string last_name {
            get {
                return ResourceManager.GetString("last_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string lastname_table {
            get {
                return ResourceManager.GetString("lastname_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string light {
            get {
                return ResourceManager.GetString("light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string login_welcome {
            get {
                return ResourceManager.GetString("login_welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields are mandatory..
        /// </summary>
        internal static string mandatory_fields {
            get {
                return ResourceManager.GetString("mandatory_fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to months.
        /// </summary>
        internal static string months {
            get {
                return ResourceManager.GetString("months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newest.
        /// </summary>
        internal static string newest {
            get {
                return ResourceManager.GetString("newest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newest First.
        /// </summary>
        internal static string newest_first {
            get {
                return ResourceManager.GetString("newest_first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has No Offers.
        /// </summary>
        internal static string no_offer {
            get {
                return ResourceManager.GetString("no_offer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account? .
        /// </summary>
        internal static string noacc {
            get {
                return ResourceManager.GetString("noacc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string number {
            get {
                return ResourceManager.GetString("number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer Type.
        /// </summary>
        internal static string offer_type {
            get {
                return ResourceManager.GetString("offer_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred. Please try again later..
        /// </summary>
        internal static string offer_update_error {
            get {
                return ResourceManager.GetString("offer_update_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer updated successfully..
        /// </summary>
        internal static string offer_update_success {
            get {
                return ResourceManager.GetString("offer_update_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offers.
        /// </summary>
        internal static string offers {
            get {
                return ResourceManager.GetString("offers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oldest.
        /// </summary>
        internal static string oldest {
            get {
                return ResourceManager.GetString("oldest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oldest First.
        /// </summary>
        internal static string oldest_first {
            get {
                return ResourceManager.GetString("oldest_first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to generate PDF! Try again later..
        /// </summary>
        internal static string pdf_error {
            get {
                return ResourceManager.GetString("pdf_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF generated successfully..
        /// </summary>
        internal static string pdf_success {
            get {
                return ResourceManager.GetString("pdf_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period of validity (in months).
        /// </summary>
        internal static string period {
            get {
                return ResourceManager.GetString("period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number:.
        /// </summary>
        internal static string phone_num {
            get {
                return ResourceManager.GetString("phone_num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string phonenum_table {
            get {
                return ResourceManager.GetString("phonenum_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realestate Type.
        /// </summary>
        internal static string realestate_type {
            get {
                return ResourceManager.GetString("realestate_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating realestate. Try again later..
        /// </summary>
        internal static string realestate_update_error {
            get {
                return ResourceManager.GetString("realestate_update_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realestates.
        /// </summary>
        internal static string realestates {
            get {
                return ResourceManager.GetString("realestates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string save_edit {
            get {
                return ResourceManager.GetString("save_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as PDF.
        /// </summary>
        internal static string save_pdf {
            get {
                return ResourceManager.GetString("save_pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        internal static string select_language {
            get {
                return ResourceManager.GetString("select_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Theme.
        /// </summary>
        internal static string select_theme {
            get {
                return ResourceManager.GetString("select_theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serbian.
        /// </summary>
        internal static string serbian {
            get {
                return ResourceManager.GetString("serbian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Description.
        /// </summary>
        internal static string short_desc {
            get {
                return ResourceManager.GetString("short_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign date.
        /// </summary>
        internal static string sign_date {
            get {
                return ResourceManager.GetString("sign_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        internal static string signup {
            get {
                return ResourceManager.GetString("signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred. Please try again later..
        /// </summary>
        internal static string signup_error {
            get {
                return ResourceManager.GetString("signup_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort By.
        /// </summary>
        internal static string sort {
            get {
                return ResourceManager.GetString("sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square meterage.
        /// </summary>
        internal static string sqr_footage {
            get {
                return ResourceManager.GetString("sqr_footage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string status_table {
            get {
                return ResourceManager.GetString("status_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        internal static string street {
            get {
                return ResourceManager.GetString("street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with that username already exists..
        /// </summary>
        internal static string user_exists {
            get {
                return ResourceManager.GetString("user_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        internal static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string username_table {
            get {
                return ResourceManager.GetString("username_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid for.
        /// </summary>
        internal static string valid_for {
            get {
                return ResourceManager.GetString("valid_for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must wait for an administrator to activate your account..
        /// </summary>
        internal static string wait_for_activation {
            get {
                return ResourceManager.GetString("wait_for_activation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        internal static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome Admin!.
        /// </summary>
        internal static string welcome_admin {
            get {
                return ResourceManager.GetString("welcome_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome agent!.
        /// </summary>
        internal static string welcome_agent {
            get {
                return ResourceManager.GetString("welcome_agent", resourceCulture);
            }
        }
    }
}
